package com.example.LearnEnglishBot.model.wordList;

public enum ConditionWordList {
    SELECT_ALL,
    DELETE_LIST,
    DELETE_ALL,
    WAIT_FOR_NAME,
    WAIT_FOR_CATEGORY,
    WAIT_FOR_ENGLISH_LEVEL,
    WAIT_FOR_ACCESS_LEVEL,
    WAIT_FOR_NUMBER_OF_LIST,
    WAIT_FOR_CATEGORY_OF_SUGGESTED_TEST,
    SELECTED_LIST_FOR_ACTIVITY,
    WAIT_FOR_TITLE_OF_ADDED_LIST,
    WAIT_FOR_SELECT_LIST,
    NONE
}
